services:
  deepseek-cli:
    build: .
    image: deepseek-kit:latest
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    stdin_open: true
    tty: true
    command: ["chat", "Hello from Docker!"]

  test:
    build: .
    image: deepseek-kit:latest
    working_dir: /app
    volumes:
      - .:/app:ro
    command: ["swift", "test"]
